development:
  adapter: mysql2
  database: fatidd_development
  pool: 5
  timeout: 5000
  host: localhost
  username: root
  password: Qwerty123!

production:
  adapter: mysql2
  database: fatidd_production
  pool: 5
  timeout: 5000
  host: localhost
  username: root
  password: Qwerty123!
